name: Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up C++ environment
              uses: actions/setup-cpp@v2
              with:
                    cpp-version: '20'

            - name: Build project
              run: |
                    mkdir build
                    cd build
                    cmake ..
                    make

            # - name: Archive build artifacts
            #     uses: actions/upload-artifact@v2
            #     with:
            #         name: build-artifacts
            #         path: build
