name: reviewdog
on: [pull_request]
jobs:
  infer:
    name: runner / infer
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Setup Infer
        uses: srz-zumix/setup-infer@v1
      - name: Infer
        run: |
            cmake -B build
            cd build
            infer -- make
      - name: Check Infer report
        uses: srz-zumix/reviewdog-action-infer@v1
        with:
          reporter: github-pr-review # Default is github-pr-check
